FROM alanfx/rhel5
MAINTAINER Ruslan Valiyev <valiyev@unicc.org>

# Passed during the build with --build-arg
ARG KATELLO_HOST
ARG KATELLO_RPM
ARG KATELLO_ORG
ARG KATELLO_USER
ARG KATELLO_PASS
ARG BITBUCKET
ARG REPO

# Register first to be able to yum install
COPY ["./lib", "./lib"]
RUN rm -f /etc/yum.repos.d/*
RUN subscription-manager remove --all ; subscription-manager unregister ; subscription-manager clean
RUN source ./lib/katello_ops.sh && register $HOSTNAME rhel-5-x86_64

# Install 'puppet', 'tar', 'git' + 'puppetlabs-stdlib'
RUN yum --nogpg -y install puppet git tar
RUN puppet module install puppetlabs-stdlib
RUN yum clean all

# Unscubscribe and remove from Katello when you're done
RUN source ./lib/katello_ops.sh && unregister $HOSTNAME
